# cloudbuild.yaml
substitutions:
  _PROJECT_ID: "portaldoprofessor"
  _REGION: "us-central1"
  _REPO: "portal-repo"
  _IMAGE: "portal-api"
  # >>> AQUI: escolha o teu requirements "completo":
  _REQ_PATH: "backend/requirements.txt"

options:
  logging: CLOUD_LOGGING_ONLY
#c
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg","REQUIREMENTS_PATH=${_REQ_PATH}",
        "-t","${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run","deploy","gerenciador-turmas",
        "--image","${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",      # troque para --no-allow-unauthenticated se quiser privado (IAM)
        "--port","8080",
        "--memory","512Mi",
        "--concurrency","80",
        "--max-instances","10"
      ]

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:${SHORT_SHA}"
