services:
  - type: web
    name: portal-professor-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/docs"
    autoDeploy: true
    # Variáveis de ambiente do backend (definidas no Dashboard do Render)
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRE_MINUTES
        value: "120"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      # Opcional: se seu backend usa CORS dinâmico por env
      - key: FRONTEND_ORIGIN
        sync: false

  - type: static_site
    name: portal-professor-frontend
    plan: free
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: "frontend/dist"
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      # SPA fallback para React Router
      - type: rewrite
        source: "/*"
        destination: "/index.html"
