services:
  - type: web
    name: portal-professor-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/docs"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRE_MINUTES
        value: "120"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false

  - type: web
    name: portal-professor-frontend
    runtime: static
    plan: free
    buildCommand: "cd frontend && npm ci && npm run build"
    publishPath: "frontend/dist"
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: NODE_VERSION
        value: "18"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
